spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql-db-cours?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  stripe:
    key: ${STRIPE_SECRET_KEY}
  ai:
    openai:
      base-url: https://openrouter.ai/v1
      api-key: ${OPENROUTER_API_KEY}
      model: meta-llama/llama-3.1-8b-instruct
    opener:
        key: ${OPENAI_API_KEY}
        base-url: https://api.openai.com/v1
  autoconfigure:
    exclude: org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration
