spring:
  datasource:
    url: jdbc:mysql://mysql-db-events:3306/events?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect



  eureka:
    client:
      service-url:
        defaultZone: http://discovery:8761/eureka  # Discovery service URL
      fetch-registry: true
      register-with-eureka: true
    instance:
      metadata-map:
        description: Event Service Microservice



logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG


